import mcpi.minecraft as minecraft
import mcpi.block as block
import random
import time

#written by @ncscomputing / @warksraspijam

BlocksList = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]

mc = minecraft.Minecraft.create()

def StarTrooper(B1,B2):
    row0 = [B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1]
    row1 = [B1,B1,B1,B1,B1,B1,B1,B1,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1]
    row2 = [B1,B1,B1,B1,B1,B1,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1,B1,B1,B1,B1,B1,B1]
    row3 = [B1,B1,B1,B1,B1,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1,B1,B1,B1,B1,B1]
    row4 = [B1,B1,B1,B1,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1,B1,B1,B1,B1]
    row5 = [B1,B1,B1,B1,B2,B1,B1,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B2,B1,B1,B1,B1,B1,B1,B1]
    row6 = [B1,B1,B1,B1,B2,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B2,B1,B1,B1,B1,B1,B1,B1]
    row7 = [B1,B1,B1,B1,B2,B2,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B2,B2,B1,B1,B1,B1,B1,B1,B1]
    row8 = [B1,B1,B1,B1,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1,B1,B1,B1,B1]
    row9 = [B1,B1,B1,B1,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1,B1,B1,B1,B1]
    row10 =[B1,B1,B1,B1,B2,B2,B1,B1,B1,B1,B1,B1,B1,B2,B1,B1,B1,B1,B1,B1,B1,B2,B2,B1,B1,B1,B1,B1,B1,B1]
    row11 =[B1,B1,B1,B1,B2,B2,B1,B1,B1,B1,B1,B1,B2,B2,B2,B1,B1,B1,B1,B1,B1,B2,B2,B1,B1,B1,B1,B1,B1,B1]
    row12 =[B1,B1,B1,B1,B2,B2,B1,B1,B1,B1,B1,B2,B2,B2,B2,B2,B1,B1,B1,B1,B1,B2,B2,B1,B1,B1,B1,B1,B1,B1]
    row13 =[B1,B1,B1,B2,B2,B2,B1,B1,B1,B1,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1,B1,B2,B2,B2,B1,B1,B1,B1,B1,B1]
    row14 =[B1,B1,B2,B2,B2,B2,B1,B1,B1,B2,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1,B2,B1,B2,B2,B1,B1,B1,B1,B1]
    row15 =[B1,B1,B2,B2,B2,B1,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B1,B2,B2,B1,B1,B1,B1,B1]
    row16 =[B1,B1,B2,B2,B2,B1,B1,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B2,B2,B1,B1,B1,B1,B1]
    row17 =[B1,B1,B2,B2,B2,B1,B2,B2,B2,B2,B2,B2,B1,B1,B1,B2,B2,B2,B2,B2,B2,B2,B1,B2,B2,B1,B1,B1,B1,B1]
    row18 =[B1,B1,B2,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1,B1,B1,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1]
    row19 =[B1,B1,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B2,B2,B2,B1,B1,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1,B1,B1]
    rowB2 =[B1,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B2,B2,B2,B2,B2,B1,B1,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1,B1]
    row21 =[B1,B2,B2,B2,B2,B2,B2,B2,B1,B1,B2,B2,B2,B2,B2,B2,B2,B1,B1,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1,B1]
    row22 =[B1,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B1,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1,B1]
    row23 =[B1,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1,B1,B1]
    row24 =[B1,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B1,B2,B1,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1,B1,B1]
    row25= [B1,B1,B1,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B2,B1,B1,B2,B2,B2,B2,B2,B1,B1,B2,B2,B1,B1,B1,B1,B1]
    row26= [B1,B1,B1,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1,B1,B1,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1,B1,B1,B1]
    row27= [B1,B1,B1,B1,B1,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1,B1,B1,B1,B1]
    row28 =[B1,B1,B1,B1,B1,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B2,B1,B1,B1,B1,B1,B1,B1]
    row29 =[B1,B1,B1,B1,B1,B1,B1,B2,B2,B2,B2,B2,B1,B1,B1,B1,B1,B2,B2,B2,B2,B2,B1,B1,B1,B1,B1,B1,B1,B1]
    row30 =[B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1]
    TempList = [row30,row29,row28,row27,row26,row25,row24,row23,row22,row21,rowB2,row19,row18,row17,row16,row15,row14,row13,row12,row11,row10,row9,row8,row7,row6,row5,row4,row3,row2,row1,row0]
    return TempList

def RandomStormy(B1,BlocksList):
    row0 = [B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1]
    row1 = [B1,B1,B1,B1,B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1]
    row2 = [B1,B1,B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1,B1,B1,B1]
    row3 = [B1,B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1,B1,B1]
    row4 = [B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1,B1]
    row5 = [B1,B1,B1,B1,(35,random.choice(BlocksList)),B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1,B1]
    row6 = [B1,B1,B1,B1,(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1,B1]
    row7 = [B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1,B1]
    row8 = [B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1,B1]
    row9 = [B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1,B1]
    row10 =[B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1,B1,(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1,B1]
    row11 =[B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1,B1]
    row12 =[B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1,B1]
    row13 =[B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1]
    row14 =[B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,(35,random.choice(BlocksList)),B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1]
    row15 =[B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1]
    row16 =[B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1]
    row17 =[B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1]
    row18 =[B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1]
    row19 =[B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1]
    row20 =[B1,(35,random.choice(BlocksList)),B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1]
    row21 =[B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1]
    row22 =[B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1]
    row23 =[B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1]
    row24 =[B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,(35,random.choice(BlocksList)),B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1]
    row25= [B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,(35,random.choice(BlocksList)),B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1]
    row26= [B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1]
    row27= [B1,B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1,B1]
    row28 =[B1,B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1,B1]
    row29 =[B1,B1,B1,B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),B1,B1,B1,B1,B1,B1,B1,B1]
    row30 =[B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1,B1]
    TempList = [row30,row29,row28,row27,row26,row25,row24,row23,row22,row21,row20,row19,row18,row17,row16,row15,row14,row13,row12,row11,row10,row9,row8,row7,row6,row5,row4,row3,row2,row1,row0]
    return TempList

def RandomWall():
    row0 = [(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row1 = [(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row2 = [(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row3 = [(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row4 = [(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row5 = [(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row6 = [(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row7 = [(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row8 = [(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row9 = [(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row10 =[(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row11 =[(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row12 =[(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row13 =[(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row14 =[(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row15 =[(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row16 =[(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row17 =[(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row18 =[(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row19 =[(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row20 =[(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row21 =[(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row22 =[(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row23 =[(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row24 =[(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row25= [(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row26= [(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row27= [(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row28 =[(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row29 =[(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    row30 =[(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList)),(35,random.choice(BlocksList))]
    TempList = [row30,row29,row28,row27,row26,row25,row24,row23,row22,row21,row20,row19,row18,row17,row16,row15,row14,row13,row12,row11,row10,row9,row8,row7,row6,row5,row4,row3,row2,row1,row0]
    return TempList


def PrintWall(ImportedList):

    pos = mc.player.getTilePos()
    mc.player.setPos(pos.x,pos.y,pos.z)

    myList = ImportedList
    

    for row in range (0,30):
        for column in range (0,30):
            
            mc.setBlock(pos.x+column,pos.y+row,pos.z-20,myList[row][column])    
            

while True:
    PrintWall(StarTrooper((35,random.choice(BlocksList)),(35,random.choice(BlocksList))))
    time.sleep(0.5)
    PrintWall(RandomStormy((35,random.choice(BlocksList)),BlocksList))
    time.sleep(0.5)
    PrintWall(RandomWall())
    time.sleep(0.5)
